### ISSUE TITLE
Crash when clicking on singleplayer

### ISSUE THREAD

**Issue by CoohCooh** [AlmostReliable/almostunified#100]
### Minecraft Version

1.21.1

### Mod Version

1.2.0

### Crash Report

https://pastebin.com/bJDcmyG1

### Log

https://pastebin.com/qaExt7p0

### Additions and Modifications

Yes

### Additions and Modifications Description

After I added the list of mods below, the problem occurred:

Bad Wither No Cookie - Reloaded
More Red
Hyperbox
Better Animations Collection
AE2 JEI Integration
YUNG's Better Desert Temples
YUNG's Better Dungeon
YUNG's Better End Island
YUNG's Better Jungle Temples
YUNG's Better Mineshafts
YUNG's Better Nether Fortresses
YUNG's Better Ocean Monuments
YUNG's Better Strongholds
YUNG's Better Witch Huts
YUNG's Bridges
Modular Golems
Industrial Foregoing Souls
Better Trims

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Could you try to find the minimal reproduction example? My time is currently very limited and it would be extremely helpful if you find out which combination of mods is causing this.

**Comment by CoohCooh** [comment]
Alright, I'll take a look and share the results with you.

**Comment by SrNadien** [comment]
> ¿Podrías intentar encontrar el ejemplo de reproducción mínima? Actualmente tengo muy poco tiempo y sería extremadamente útil si descubrieras qué combinación de mods está causando esto.



> ¿Podrías intentar encontrar el ejemplo de reproducción mínima? Actualmente tengo muy poco tiempo y sería extremadamente útil si descubrieras qué combinación de mods está causando esto.

It happened to me too It happens when you click the single player button, it crashes and that crash comes out.

**Comment by CoohCooh** [comment]
I haven't had any results yet. I'll have to disable over 300 mods to find the problem.

**Comment by rlnt** [comment]
I understood it like the issue occurred within the small collection of mods you mentioned in the initial post.

**Comment by CoohCooh** [comment]
Yes, but I disabled them, and the crash still happens

**Comment by CoohCooh** [comment]
I haven't been able to find the error yet. My modpack only works after I disable Almost Unified. Unfortunately, I don't have time to identify this issue, but hopefully, it will be resolved soon.

**Comment by rlnt** [comment]
Could you do me a favor and use this JAR instead? It should log the affected recipe. Just run it in your usual environment and share the log here, please.

Since I can't upload JARs to GitHub, it's a zip file. You can just rename the file from `.zip` to `.jar` and it works fine.
[almostunified-neoforge-1.21.1-1.2.0.zip](https://github.com/user-attachments/files/17476250/almostunified-neoforge-1.21.1-1.2.0.zip)

**Comment by rlnt** [comment]
The recipes with invalid recipe types are now being skipped to prevent a crash but I would still like to see the log with the custom JAR because I want to know which mod is causing this.
