### ISSUE TITLE
Game Crashed whilst mouseclicked event Handler Error

### ISSUE THREAD

**Issue by Devilswarchild** [AlmostReliable/almostunified#101]
### Minecraft Version

1.21.1

### Mod Version

neoforge-1.21.1-1.2.0.jar

### Crash Report

https://mclo.gs/gCcLqT1

### Log

https://mclo.gs/KEKxiHs

### Additions and Modifications

Yes

### Additions and Modifications Description

unreleased update to my public modpack: https://www.curseforge.com/minecraft/modpacks/minecolonies-dimensional-adventure

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Stellaris tag issue https://github.com/AlmostReliable/almostunified/issues/99

**Comment by rlnt** [comment]
Wait you are on Stellaris 1.1.7 already which should include the fix. I will need to investigate. Sorry.

**Comment by Devilswarchild** [comment]
yes current version of stellaris in this build is 1.1.7

**Comment by rlnt** [comment]
Would it be possible to get an instance export of this update? I need to see the configs and the mods involved. You can send it via Discord if you don't want to share it in public. Either join our Discord or message me directly. My username is `rlnt.`.

**Comment by Devilswarchild** [comment]
the configs are all default generated. I havent even gotten to a point of editing them but sure I can send it via discord

also the build in question is labeled as 0.0.2-alpha on my modpack page

**Comment by ModernGamingWorld** [comment]
I am also getting this error.

The crash is caused by a NullPointerException related to the transformerResult not being set, which occurs during the handling of the mouseClicked event. The error points to the mod "Almost Unified" and its interaction with the recipe manager.

Here's the critical part of the crash report:

java.lang.NullPointerException: transformerResult not set
    at com.almostreliable.unified.utils.DebugHandler.collectRecipeError(DebugHandler.java:79)
    at com.almostreliable.unified.AlmostUnifiedCommon.onRecipeManagerError(AlmostUnifiedCommon.java:50)


The mod "Almost Unified" appears to be involved in handling recipe errors, and the mouseClicked event is triggering this issue. The mod may be encountering a problem with recipes or resource reloads that it cannot handle correctly, leading to the crash.

**Comment by rlnt** [comment]
We are aware of the crash. Commenting "I have it too" isn't helpful. We know what's causing the crash, we just didn't have time to update the mod yet. An explanation of the crash log is not necessary.

It would be much more beneficial to share your mod list so we can see which mods are involved. Attaching the crash report would be enough for that.

**Comment by ModernGamingWorld** [comment]
[crash-2024-10-22_11.25.33-client.txt](https://github.com/user-attachments/files/17479399/crash-2024-10-22_11.25.33-client.txt)

Still crashing with the mod active, Had to disable it just to load into my test world

**Comment by rlnt** [comment]
Something is crashing the unification process in your case. I need the full log.

**Comment by ModernGamingWorld** [comment]
[latest.log](https://github.com/user-attachments/files/17482567/latest.log)
[debug.log](https://github.com/user-attachments/files/17482570/debug.log)

**Comment by rlnt** [comment]
Please open a thread on Discord. The logs don't belong to your crash. They don't include the crash and the instance doesn't even have Almost Unified installed.
