### ISSUE TITLE
1.18 Add support for "all the ores" and Industrial Reborn

### ISSUE THREAD

**Issue by jusitnboggs** [AlmostReliable/almostunified#103]
### Describe the feature/addition!

Add support for "all the ores" and Industrial Reborn I'm on 1.18.

### Why would like to see this feature/addition?

So that the ore are unified etc.

**Comment by rlnt** [comment]
All the Ores is supported and is just a matter of configuration. Team ATM is using the two mods in combination in their packs. New support for other mods won't be added for 1.18. The version is outdated and no longer maintained.
