### ISSUE TITLE
Iron nugget unobtainable

### ISSUE THREAD

**Issue by phooenixdassmatte** [AlmostReliable/almostunified#105]
### Minecraft Version

1.20.1

### Mod Version

0.9.4

### Describe the bug!

We added this mod to fix some inconsistencys with tin because we have 2 of them, and it fixed a handful of other stuff aswell, but it made iron nuggets unobtainable because iron ingots become thallasium nuggets from the mod "better end" instead.
![iron ingot makes thallasiun nugget](https://github.com/user-attachments/assets/876b88af-0b73-422c-875f-6de346776df2)

### Additions and Modifications

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by phooenixdassmatte** [comment]
I can see now that the thallasium ingot from better end was removed and replaced with iron ingot.
![thallasium ingot](https://github.com/user-attachments/assets/776b5a4d-8917-47a2-95f5-2bf6a3038fbe)

**Comment by rlnt** [comment]
Configuration issue. Read this wiki part to fix it.
https://github.com/AlmostReliable/almostunified/wiki/Mod-Support#better-nether--better-end

<blockquote><img src="https://opengraph.githubassets.com/90338c85ae2d98763387ff4137e7b461eaf9fad73637ae155f49efc9044962f2/AlmostReliable/almostunified" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmostReliable/almostunified/wiki/Mod-Support">Mod Support</a></strong></div><div>A Minecraft mod to unify resources. Contribute to AlmostReliable/almostunified development by creating an account on GitHub.</div></blockquote>
