### ISSUE TITLE
Amethyst Imbuement recipe compat

### ISSUE THREAD

**Issue by Sunconure11** [AlmostReliable/almostunified#13]
### Describe the feature/addition!

Recipes altered by this mod don’t seem to be overtly compatible with it.

### Why would like to see this feature/addition?

Read above

**Comment by rlnt** [comment]
Well, their recipe JSONs have a *very* odd syntax, to say the least. This needs some compat work. Thanks for reporting.
https://github.com/fzzyhmstrs/ai/blob/master/src/main/resources/data/amethyst_imbuement/recipes/ametrine_imbuing.json

**Comment by LLytho** [comment]
Resolved in b8c924ca2b52485b55c5bb16b74b998eeb27dfa0 (1.18.2) and bed00c94152f8c3e23aea1ffa6ee94e1b808480c (1.19). Will be in v0.1.2
