### ISSUE TITLE
Unifiy Sawdust

### ISSUE THREAD

**Issue by benbenlaw** [AlmostReliable/almostunified#14]
### Describe the feature/addition!

Would be nice if sawdust was also unified quite a few mods seem to add it 

### Why would like to see this feature/addition?

it would be very helpful :)

**Comment by rlnt** [comment]
You have to add it to the config. If all saw dusts are tagged correctly, that should already be possible.

If not all saw dusts have a tag in common, you can add one manually with KubeJS and add it to the config. The unification runs after the tag event and before the recipes event so it will make use of custom tags as well.

When you still have issues with it after trying the mentioned steps, please join the Discord which will be mentioned in the next reply of the bot.

**Comment by benbenlaw** [comment]
im dumb sorry haha thanks :)
