### ISSUE TITLE
Crash on Startup with KubeJS `NoSuchFieldError: type`

### ISSUE THREAD

**Issue by NielsPilgaard** [AlmostReliable/almostunified#20]
### Version

almostunified-forge-1.19.2-0.2.3

### Crash Report

https://gist.github.com/NielsPilgaard/473f662fa31b3ed2592a975a721e9d24

### Log

https://gist.github.com/NielsPilgaard/db35e2943b60a3a19c033f01fd29334b

### Additional Context

No

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by LLytho** [comment]
I see Rhino is pushing new unnecessary changes again. Nice... Will fix it tomorrow

**Comment by LLytho** [comment]
~Uploaded to CF, should be available soon.~ Will fix another issue and then upload it to CF. Thanks for the report.
