### ISSUE TITLE
Doesn't appear to work for Immersive Engineering and Thermal Slag

### ISSUE THREAD

**Issue by MuteTiefling** [AlmostReliable/almostunified#25]
### Version

almostunified-forge-1.19.2-0.2.6

### Describe the bug!

```js
  "modPriorities": [
    "minecraft",
    "kubejs",
    "crafttweaker",
    "create",
    "thermal",
    "mekanism",
    "immersiveengineering",
    "blue_skies"
  ],
```
```js
  "tags": [
    "forge:nuggets/{material}",
    "forge:dusts/{material}",
    "forge:gears/{material}",
    "forge:gems/{material}",
    "forge:ingots/{material}",
    "forge:raw_materials/{material}",
    "forge:ores/{material}",
    "forge:plates/{material}",
    "forge:rods/{material}",
    "forge:storage_blocks/{material}",
    "forge:slag",
    "forge:coal_coke",
    "forge:sawdust"
  ],
```
`forge:slag` is present in the tags list, both types of slag share the tag, yet IE machines continue to show IE slag as output, even though Thermal should be priority:

![image](https://user-images.githubusercontent.com/9543430/204682642-3c357c66-f398-475e-bb9c-ea461fc445b8.png)
![image](https://user-images.githubusercontent.com/9543430/204682665-1d5a4ab1-3968-4550-872b-5b33e5d5597b.png)

![image](https://user-images.githubusercontent.com/9543430/204682689-ae5b6b80-9ab3-4b86-9b11-5c814a76b6e7.png)

### Log

https://gist.github.com/MuteTiefling/ddbfe60dea4a16b43539482c317f9198

### Additional Context

Yes

### Modifications

enigmatica 9 development pack

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Could you activate everything inside the `debug.json` config, do a reload or a world rejoin, go to `logs/almostunified` and zip up everything in there and send it?

Need to see what's going on. In 1.19, it's very tricky to get these mods running in a dev environment so a bit of insight would be very helpful.

**Comment by rlnt** [comment]
Nevermind, they have an unsupported key in their recipe. Will be fixed.

**Comment by MuteTiefling** [comment]
Awesome, thanks!
