### ISSUE TITLE
BetterEnd Thallasium not showing up as valid Ingot

### ISSUE THREAD

**Issue by Gamerbolts** [AlmostReliable/almostunified#29]
### Version

2.1.2

### Describe the bug!

I am creating a modpack and while going through and testing I found that Almost Unified is making the Thallasium from BetterENnd not show up in REI or allow anything crafted with that ingot to work. Other ingots work and show up from betterend. This is my config file.

https://pastebin.com/EynNUzXm

### Log

https://gist.github.com/Gamerbolts/129178e3519a2fa5afc15587e8370084

### Additional Context

Yes

### Modifications

It is in my modpack

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by LLytho** [comment]
Try to put the iron tag into `ignoredTags`. Iirc Thallasium is just some iron type they use for recipes.

**Comment by Gamerbolts** [comment]
Hmm I did this but it did not work.

  "ignoredTags": [
  "c:ingots/iron"
  ],

**Comment by LLytho** [comment]
isn't it `c:iron_ingots` ?

**Comment by Gamerbolts** [comment]
oh that may be it, I wasn't sure of fabrics tags. I did however fix it with this

  "ignoredItems": [
	"betterend:thallasium_ingot"
  ],

Thanks for the help! :)

**Comment by SunsetJesus4653** [comment]
> Try to put the iron tag into `ignoredTags`. Iirc Thallasium is just some iron type they use for recipes.

Where is ignoredTags?
