### ISSUE TITLE
You are a hero!

### ISSUE THREAD

**Issue by Testing123-svg** [AlmostReliable/almostunified#3]
### Version

AlmostUnified-Forge-1.18.2-0.0.5

### Describe the bug!

Thanks man! I wanted to leave a comment on curseforge. But you made me enjoy my world again! A week ago I was looking for something exactly like this!

### Additional Context

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
Thank you for the kind words but we'd appreciate it if you used Discord next time or just star the GitHub project. That's enough feedback. Glad you like it. 💚
