### ISSUE TITLE
Bug with Better Nether [Cincanite] replacing Iron items 

### ISSUE THREAD

**Issue by VodkaKDA** [AlmostReliable/almostunified#30]
### Version

1.18.2

### Describe the bug!

basically i noticed that iron nuggets to some tools can't be made with Iron because it seems to unify iron under an ore in Better Nether called "Cinnanite" (spelled it wrong my bad) but yeah its a yellow metal in the better nether mod. just wanted to list the issue for you to see if it can be fixed at all 

### Additional Context

Yes

### Modifications

only other mods on the server are Create Fabric, Better End, Mythic Metals and Industrial Revolution, Gobber, and Simply Swords

### Did the issue happen in singleplayer or on a server?

Server

**Comment by rlnt** [comment]
Please search other issue submissions first before creating a new one: https://github.com/AlmostReliable/almostunified/issues/29

**Comment by rlnt** [comment]
Just to make this clear for future reference. The mods come from the same devs and they decided to use vanilla tags for some reason. The solution is to ignore the items or the tags. It just requires some config tweaking.

**Comment by VodkaKDA** [comment]
Ah my apologies, i didn't notice thread #30 i was just getting so many bug reports issued to me that i made a post in haste but thank you for your time and response to my thread. loving the mod though makes things easier for the server!

**Comment by rlnt** [comment]
Glad you like it.
Sadly, there can't be a universal solution for everything but we try to cover as much as we can. The rest is up to the pack dev with the help of the configs or something like KubeJS. 😅
