### ISSUE TITLE
Missing default tags on Fabric

### ISSUE THREAD

**Issue by AsheX1** [AlmostReliable/almostunified#31]
### Version

1.19.2

### Describe the bug!

im using fabric and the last version of almostunified but i does not seems to work 
keep getting techreborn and modern_industrialization raw tin etc

i even add the them to the unify.json but looking back the json file after i boot up the client or server there gone again

### Crash Report

/

### Log

/

### Additional Context

Yes

### Modifications

just mods that new stuff and biomes nothing that change's ore's nothing that unify's anything

### Did the issue happen in singleplayer or on a server?

Both

**Comment by AsheX1** [comment]
they seems to be in bak file now but nothing seems to work so far

**Comment by LLytho** [comment]
If it creates a bak file the json you provide is wrong. Use an online json validator or vs code to see what wrong.

**Comment by AsheX1** [comment]
gimie few min

**Comment by AsheX1** [comment]
i think i forgot to add ,

**Comment by AsheX1** [comment]
oke adding in the , seems to have fixed the bak file not coming back anymore

but still getting raw tin from both tech reborn and modern_industrialization

**Comment by AsheX1** [comment]
techreborn is on top of modern_industrialization in the json file so if i mine modern_industrialization tin ore im supposed to get techreborn raw tin but its not working and keep getting the  modern_industrialization raw tin

**Comment by AsheX1** [comment]
modern_industrialization also just updated to 1.5.0 version im still on 1.4.2 of that

**Comment by LLytho** [comment]
Can you please join our Discord and use the support threads and provide the configs and the debug dump? Using Github issues as chatroom is not the best idea 😅

**Comment by AsheX1** [comment]
i made a post

**Comment by rlnt** [comment]
The issue originates from missing default tags which can be seen here: https://github.com/TeamAOF/All-of-Fabric-6/blob/main/config/almostunified/unify.json#L42-L43

<blockquote><img src="https://opengraph.githubassets.com/3e065f88a782904f7b06cbed3815cb24dbdf339245e3331182c8d97e279837a4/TeamAOF/All-of-Fabric-6" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/TeamAOF/All-of-Fabric-6">All-of-Fabric-6/unify.json at main · TeamAOF/All-of-Fabric-6</a></strong></div><div>Modpack containing the latest & best of Fabric on 1.19 - All-of-Fabric-6/unify.json at main · TeamAOF/All-of-Fabric-6</div></blockquote>
