### ISSUE TITLE
Crash when opening search tab in creative mode

### ISSUE THREAD

**Issue by evhub** [AlmostReliable/almostunified#33]
### Version

1.19.2-0.3.4

### Crash Report

https://gist.github.com/evhub/81d195a914ba6b0432c298fc3a0604e8

### Log

`latest.log` was too big to fit in a gist, but here's the most recent bit: https://gist.github.com/evhub/1b83885109f3746927040a686365a442

### Additional Context

Yes

### Modifications

Mod list is in the crash report.

### Did the crash happen in singleplayer or on a server?

Client-side crash while connected to a dedicated server

**Comment by rlnt** [comment]
Update AU and Cucumber Lib. This was already fixed.

**Comment by rlnt** [comment]
If you are still facing issues after updating the mods, feel free to open another issue. :)
