### ISSUE TITLE
[compatibility issue] Immersive Engineering and Ad Astra (Cables)

### ISSUE THREAD

**Issue by ImTemper** [AlmostReliable/almostunified#34]
### Version

1.19.2

### Describe the bug!

I believe when this mod is used with both immersive enginnering and Ad Astra it removes the ad astra cables from the game which makes many functions of the mod much harder to use. The cables from immersive engineering are not removed but do not work with ad astra. I am reporting this here as when I removed this mod, the cables from ad astra were available to find again and worked fine. I am unsure if any other items are changed, removed or edited, I only noticed the cables.

### Additional Context

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Not a mod issue but a configuration one.
If you rely on the Ad Astra cables, you could define Ad Astra as a priority mod so their items don't become hidden.

Alternatively, you could specify Ad-Astra as the priority mod for the cable tag only. This is up to the pack dev, not the mod.

**Comment by ImTemper** [comment]
Okay makes sense, my bad
