### ISSUE TITLE
Documented ore drop unification does not work

### ISSUE THREAD

**Issue by Martmists-GH** [AlmostReliable/almostunified#36]
### Version

v1.19.2-0.3.5

### Describe the bug!

Using the following script from the wiki (adapted to 1.19.2 following LootJS docs):
```js
// server_scripts/unify_drops.js

LootJS.modifiers(event => {
    event.addBlockLootModifier('#forge:ores').modifyLoot('#forge:raw_materials', item => {
        const replacement = AlmostUnified.getReplacementForItem(item);
        if (replacement.isEmpty()) {
            return item;
        }
        replacement.setCount(item.getCount());
        return replacement;
    });
});
```
Behavior: 
- Tin is not unified (Modern Industrialization, Tech Reborn)
- Lead is not unified (Modern Industrialization, Tech Reborn)
- Silver is not unified (Mythic Metals, Tech Reborn, Bewitchment)
- Salt is not unified (Modern Industrialization, Bewitchment)

### Crash Report

N/A

### Log

https://mclo.gs/DGYBu9o

### Additional Context

Yes

### Modifications

See log for mod list

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
You are using a Forge tag for your Fabric mods. Please don't open issues before talking to us. This is a support case.
