### ISSUE TITLE
Incompatibility between AlmostUnified and Miskatonic Mysteries

### ISSUE THREAD

**Issue by Marciapiede** [AlmostReliable/almostunified#4]
### Version

mod version 0.0.9 minecrfat 1.18.2

### Describe the bug!

When you install both Miskatonic Myesteries and Almostunified the Necronomicon stops working and shows this error :
![image](https://user-images.githubusercontent.com/109106459/190876088-0a7ccf56-b1c4-4d0a-aacb-1e7675ef2287.png)

Tested with just those 2 mods (and dependecises) on minecraft 1.18.2, MM version 0.1.3, patchouli version 71.1, fabric loader 0.14.9, fabric API 0.58.0 and Almostunified 0.0.9 (also tested with the version released before)

### Log

https://gist.github.com/Marciapiede/603d8e8eaeab00aa036a2a0ecb983b57

### Additional Context

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
We got a similar report on our Discord today, also with Patchouli.

It looks like books that show recipes rely on the original recipe ID which we change so it's clearly visible to the end user that Almost Unified modified the recipe in some way and to avoid reports to other authors although they have nothing to do with the recipe.

Our current idea is to add a config option where you can add recipes that should not get a new ID. Otherwise, we would have to PR something to Patchouli that fixes this issue. This might take a little while depending on the complexity of the problem.

As a workaround, you can add the recipe to the ignore list of Almost Unified so the ID does not change.

**Comment by Kanzaji** [comment]
I'm guessing this is also related to this problem 😅
Note: It is on Forge, Enigmatica 8 2.3.0 ^^" If you want I can create another issue for this with more details.
https://github.com/EnigmaticaModpacks/Enigmatica8/issues/280

**Comment by NielsPilgaard** [comment]
> Our current idea is to add a config option where you can add recipes that should not get a new ID. Otherwise, we would have to PR something to Patchouli that fixes this issue. This might take a little while depending on the complexity of the problem.

Could you perhaps add a config option that makes AU use the original recipe ids instead? Cause the per-recipe config is going to be brutal to fill in, with all the Patchouli manuals that exist in most packs😅

**Comment by LLytho** [comment]
> > Our current idea is to add a config option where you can add recipes that should not get a new ID. Otherwise, we would have to PR something to Patchouli that fixes this issue. This might take a little while depending on the complexity of the problem.
> 
> Could you perhaps add a config option that makes AU use the original recipe ids instead? Cause the per-recipe config is going to be brutal to fill in, with all the Patchouli manuals that exist in most packs😅

Hey, 

as Patchouli allows custom page templates, we have no chance to determine recipe ids to remap them. So we decided to revert the rename feature. Instead we will show a little icon with a tooltip. So you don't have to modify all the patchouli JSONs :D

![image](https://user-images.githubusercontent.com/29131229/191071276-ea213152-8b01-4bfd-bce6-4d605688e102.png)

**Comment by rlnt** [comment]
No need for more issue reports since they are all related. The fix is *almost* ready.
Thanks for the feedback.

> Could you perhaps add a config option that makes AU use the original recipe ids instead? Cause the per-recipe config is going to be brutal to fill in, with all the Patchouli manuals that exist in most packs😅

We figured out that would become an issue quite quickly. The little icon makes sure broken recipes are not reported to original authors and allows us to maintain the original recipe id.
