### ISSUE TITLE
Thermal Integration: Steel and Rose Gold still visible in recipes

### ISSUE THREAD

**Issue by The-Goat-HUN** [AlmostReliable/almostunified#50]
### Version

1.18.2-0.3.10

### Describe the bug!

While all the items you can make out of them DO disappear in JEI, they are still visible when viewing recipes. The config for them in Thermal Integration is set to "false", just thought I'd put it here, maybe it matters.

### Additional Context

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by GoatGamerHUN** [comment]
Sorry, it was my fault. Forgot to include the mod in the config.

**Comment by rlnt** [comment]
This issue submission seriously lacks context. What am I supposed to do with that little information?

Where are your configs, which recipes do you mean, screenshots?

**Comment by The-Goat-HUN** [comment]
![image_2023-05-12_141927884](https://github.com/AlmostReliable/almostunified/assets/46354254/de8f75a0-131a-4f27-8d74-a5e021d94215)

Configs are in the config folder, where they should be.
I mean all recipes that require Steel or Rose Gold.

![image](https://github.com/AlmostReliable/almostunified/assets/46354254/9ceb6c1d-ebbb-4b3b-a995-8a26f93487ea)
Here, JEI cycles between All The Ores and Thermal Steel.

**Comment by rlnt** [comment]
I didn't mean the config location, I mean where did you upload them to? We need to see configs to reproduce issues. If you don't provide them in your issue report, it's pretty useless.

Does cycle mean it cycles through different steel plates in the input grid? If so, that should not happen when all but one plate is hidden from JEI. If you only see Thermal steel plates in JEI and it still shows the ATO plates for you in recipes, that is a JEI issue.

**Comment by The-Goat-HUN** [comment]
Made it a .txt to be able to upload it here.
[unify.txt](https://github.com/AlmostReliable/almostunified/files/11464692/unify.txt)

By cycle, I mean only ATO and Thermal steel plates are being shown. And it's the case with all other steel and rose gold components. This means that every mod is being hidden (which is good) except for Thermal for some specific reason, which is way below ATO in the config so it shouldn't be appearing.

**Comment by rlnt** [comment]
You don't have rose gold in your config.

For the steel, that's likely a tagging issue and not a bug in AU. Please join the Discord server and open a support thread so we can help you better instead of chatting through GitHub issues.
