### ISSUE TITLE
Crash with REI

### ISSUE THREAD

**Issue by xana43** [AlmostReliable/almostunified#58]
### Version

1.20.1

### Crash Report

https://pastebin.com/Ak4V2m4j

### Log

https://gist.github.com/xana43/cfff74f2e8a5154ca4de1e7257e8a7c4

### Additional Context

Yes

### Modifications

a bunch of mods, like a BUNCH of mods mainly trying to make the world more alive and more enjoyable (stoneage to the stars as well) 

### Did the crash happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
`AlmostUnified 1.19.4-0.6.0`
you are using the wrong version
