### ISSUE TITLE
Tiny Coal Crafting

### ISSUE THREAD

**Issue by ItsDiamondWolf** [AlmostReliable/almostunified#59]
### Version

0.0.63 All the Mods 9

### Describe the bug!

Tiny coal recipe from Utilitix is also the same recipe for fire for standing torch from Additional Lights mod
![image](https://github.com/AlmostReliable/almostunified/assets/144290337/703c6c00-87be-48ef-b76b-dcc9cbfa5652)

![image](https://github.com/AlmostReliable/almostunified/assets/144290337/a903b9cf-8281-447d-91da-320cdd605346)

### Additional Context

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
Report this to the respective modpack. We don't define the recipes. This needs to be handled via the config.
