### ISSUE TITLE
Bug with recipe from Sculked mod

### ISSUE THREAD

**Issue by DeadPigman17** [AlmostReliable/almostunified#62]
### Version

(Forge) 1.19.2-0.7.2/BMC3 v20

### Describe the bug!

You can't craft the echo copper ingot from the Sculked mod. Also, when making a block of regular copper using 9 copper ingots, you get a block of echo copper instead of a block of regular copper.

### Additional Context

Yes

### Modifications

I'm using the BMC3 v20 modpack, for Forge.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Sounds more like a misconfiguration from the pack developer.
Reach out to them to fix that. Sounds like the mod added their copper block to the copper storage block tag which they should not do.
