### ISSUE TITLE
Recipe Duplication on Ore Dust not unifying

### ISSUE THREAD

**Issue by ffuentesm** [AlmostReliable/almostunified#66]
### Version

ImmersiveEngineering-1.20.1-10.0.0-169/occultism-1.20.1-1.116.0/almostunified-forge-1.20.1-0.8.0

### Describe the bug!

The issue comes from Immersive engineering as they set their gold/iron/copper/ dust smelting recipe to have 0 experience, while occultism has their recipe set to 0.7 experience. So even if the input item is unified, both recipes remain the same. Is the "experience output" something that clashes with the unification? I have IE on the Unify priority file, so I am not sure why Occultism's duplicated recipe is being shown. 
![image](https://github.com/AlmostReliable/almostunified/assets/44974827/1521f2d0-eb88-427e-a9dd-38e52c0c4b49) ![image](https://github.com/AlmostReliable/almostunified/assets/44974827/38c461fd-ad0d-4770-8252-663058a6f88a) ![image](https://github.com/AlmostReliable/almostunified/assets/44974827/30eb67d3-8572-44af-9903-cb64c1ffed65)

Because the Silver Dust Smelting recipe is being Unified. As the Silver Dust smelting is using the Occultims Exp output, as IE has a 0 exp recipe. 
![image](https://github.com/AlmostReliable/almostunified/assets/44974827/f935e701-aa0d-493f-92dd-3b2cf09fc52c)

### Additional Context

Yes

### Modifications

Just a private mod list that I play with, things like Create, IE, Occutims, EMI/JEI, Ice and Fire, JAOPCA, Ars, etc.
Nothing in the technical configs was altered. 

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
This should be handled in the duplicates config with this option: https://github.com/AlmostReliable/almostunified/wiki/Duplicate-Config#defaultduplicaterules

You can define recipe keys there, from which the values can deviate. You can then assign a rule to determine which value should be selected in the event of a conflict. The default config should have the `experience` key with the `HigherRule` by default. This is the key that defines the experience gain in smelting recipes and can be seen here: https://github.com/klikli-dev/occultism/blob/version/1.20.1/src/main/resources/data/occultism/recipes/smelting/copper_ingot_from_dust.json

Can you check if your section in your duplicates config looks like this?
```json
  "defaultDuplicateRules": {
    "ignoredFields": [
      "conditions",
      "group"
    ],
    "rules": {
      "cookingtime": "HigherRule",
      "energy": "HigherRule",
      "experience": "HigherRule"
    },
    "shouldSanitize": false
  }
  ```

**Comment by ffuentesm** [comment]
Yes, it's the same 
![image](https://github.com/AlmostReliable/almostunified/assets/44974827/a507ca8b-d0f2-4cd7-807e-243f1fbfdc73)

This really confuses me, because I got Silver Dust Unified, but for some reason, Copper/Gold/Iron are not being unified. 

Here is the IE recipe in comparison to the one in Occultims
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.1/src/generated/resources/data/immersiveengineering/recipes/smelting/copper_ingot_from_dust.json

**Comment by rlnt** [comment]
You have to add the `category` key to the ignored fields then. I haven't seen this before but seems like Immersive Engineering recipes have that key so they can't be detected as duplicates.

The following piece should be added to the `overrideDuplicateRules` where `"minecraft:crafting_shaped"` is already.
```js
  "minecraft:smelting": {
    "ignoredFields": [
      "conditions",
      "group",
      "category"
    ],
    "rules": {
      "cookingtime": "HigherRule",
      "experience": "HigherRule"
    },
    "shouldSanitize": false
  }
  ```

**Comment by ffuentesm** [comment]
Thanks, it unified into a single one. 
That's strange. Why was just gold/iron/copper, the ones not unifying if Silver, which has the same file structure, was unifying?

**Comment by rlnt** [comment]
I assume either Immersive Engineering has no category in silver related recipes, there is no silver in Immersive Engineering, or no other mod has silver besides Immersive Engineering.

Anyways, this is a thing we can improve in the mod and I would have never known without your issue submission. Thanks a lot!
The `category` key seems to be new since 1.19.3 and we didn't see that.

**Comment by ffuentesm** [comment]
Yeah, IE has silver, and I have 2 other mods that add silver.  And Silver Dust recipes. As I saw the unified recipe using EI item, with the Occultism EXP output. 

https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.1/src/generated/resources/data/immersiveengineering/recipes/smelting/ingot_silver_from_dust.json
https://github.com/klikli-dev/occultism/blob/version/1.20.1/src/main/resources/data/occultism/recipes/smelting/silver_ingot_from_dust.json

On a side note, I assume this is not being unified due to one being shaped and the other being a shapeless recipe? 
![image](https://github.com/AlmostReliable/almostunified/assets/44974827/574d470b-08b9-4e3a-b7ff-f285a5281505)

**Comment by rlnt** [comment]
Yep, only recipes with the same recipe type are being matched against each other. Whichever mod added the shapeless recipe, this should be reported.

Vanilla Minecraft is also using shaped recipes for ingots from nuggets and storage blocks from ingots.

**Comment by ffuentesm** [comment]
On a side note, I updated to the latest version of Almost Unified and EMI, where they are both compatible with each other, but I noticed that EMI does not have the AU symbol on the recipes. Is that something that EMI has to deal with?

**Comment by rlnt** [comment]
Hm, it should display. I tested it in Singleplayer and Multiplayer. Might give this another look.
Enough for this issue submission now. We have a Discord for talking😄
