### ISSUE TITLE
[1.20.1] Blood Magic Metal Not Unifying/Showing same entry twice

### ISSUE THREAD

**Issue by ffuentesm** [AlmostReliable/almostunified#71]
### Minecraft Version

1.20.1

### Mod Version

almostunified-forge-1.20.1-0.9.0

### Describe the bug!

The Demonite/Hellforged block from Blood Magic and JAOPCA are not unifying. 
I am getting a duplicated recipe after I added the StorageBlock tag to BM Demonite Block so it would unify, but the recipe is still dubled.
![image](https://github.com/AlmostReliable/almostunified/assets/44974827/86f34f73-41a0-4329-811a-03ba4a247014)

### Additions and Modifications

Yes

### Additions and Modifications Description

Just a private mod list that I play with, things like Create, IE, Occutims, EMI/JEI, Ice and Fire, JAOPCA, Ars, etc.
Nothing in the technical configs was altered.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
This is more of a support request because it probably is a tag or a configuration issue. This is vanilla crafting so unification for it is already in place. I would need to see some debug logs. Could you open a thread in the Discord?
