### ISSUE TITLE
Iron gets unified with Thallasium and Cincinnasite from BetterEnd BetterNether

### ISSUE THREAD

**Issue by Marabus69** [AlmostReliable/almostunified#73]
### Minecraft Version

1.20.1

### Mod Version

0.9.2

### Describe the bug!

When I tried to craft an iron block with iron ingots it gave me a thallasium Block so I looked into the recipe for a thallasium block with JEI and I saw that iron, thallasium and also cincinnasite all got unified. So now when I try to craft anything with iron I either get something made out of thallasium or cincinnasite and thats really annoying.

### Additions and Modifications

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
Not a mod issue. This is a configuration problem. Add the materials to the ignore list. They are tagged as iron by the mod.

**Comment by Marabus69** [comment]
I would but I just dont have any idea how that works

**Comment by rlnt** [comment]
The issue tracker is only for actual bug reports or feature requests. To get support, please join the [Discord](https://discord.com/invite/ThFnwZCyYY).

**Comment by a11ce** [comment]
For anyone else who finds this from google, the solution is to add
```json
"ignoredItems": [".*thallasium.*", ".*cincinnasite.*"]
```
to your `config/almostunified/unify.json`, as described on [this repo's wiki](https://github.com/AlmostReliable/almostunified/wiki/Mod-Support#better-nether--better-end)
