### ISSUE TITLE
JEI recipe potentially being blocked by almostunified

### ISSUE THREAD

**Issue by CountBlumiere** [AlmostReliable/almostunified#75]
### Minecraft Version

1.20.1

### Mod Version

AlmostUnified-Forge-1.20.1-0.9.2

### Describe the bug!

The dirty ore dusts from Mekanism cannot inserted, automatically or manually into the Enrichment Chamber/Factory. JEI does not show a use for the these dusts. Dirty ore dusts provided by JAOPCA as well as the dirty nether dust by Mekanism is functional, however, the core ores (iron, copper, gold, osmium, tin, lean, and uranium) from Minecraft and Mekanism are not.

However, these dusts do work in Singleplayer, if the client is launcher via curseforge, but it will not work if launcher via FTB app, or in Multiplayer in either launchers. This holds true in both Survival and Creative. 

### Additions and Modifications

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by rlnt** [comment]
This is lacking a lot of context. With the little info I get from this, it sounds more like a config issue and you should open a support thread in our [Discord](https://discord.com/invite/ThFnwZCyYY).
