### ISSUE TITLE
Custom unification config for rubber via Sinytra Connector, Tech Reborn and Industrial Foregoing

### ISSUE THREAD

**Issue by Cragsand** [AlmostReliable/almostunified#79]
### Minecraft Version

1.20.1

### Mod Version

1.20.1-093 NeoForge

### Describe the bug!

I'm trying to unify rubber between Industrial Foregoing and Tech Reborn via Synytra Connector and a custom config but I can't seem to get it to work. I've followed this guide https://github.com/AlmostReliable/almostunified/wiki/Unification-Config but I might also be missing something obvious so apologies ahead of time if that is the case.

The recipes don't unify and shows an error in the loading log.

I've added the following config:
https://gist.github.com/Cragsand/48ef1a9b806378d06f7fe45ffcb86477
![image](https://github.com/AlmostReliable/almostunified/assets/49168045/3f8f6cc4-4612-495f-83d4-8a90af18e459)

For these items:
![image](https://github.com/AlmostReliable/almostunified/assets/49168045/d491a0e9-a777-46ca-8025-a2c2c7ae2f8d)
![image](https://github.com/AlmostReliable/almostunified/assets/49168045/b4729a68-5e86-4f0c-8bcb-bfc37b1c85e7)

I get this output in the log when launching:
https://gist.github.com/Cragsand/2aee0e97d9f5da08a3b7497437140311
![image](https://github.com/AlmostReliable/almostunified/assets/49168045/7ea5e0d4-c038-4fb1-86c3-602bb19ebfb7)
They are added to the tag list though, so I'm not sure how to proceed from this. But maybe I'm not understanding this.

There may also be some funky stuff going on because Synytra is a wrapper for running Fabric mods on Forge.

Mod versions:
- TechReborn-5.8.7.jar
- RebornCore-5.8.7.jar
- Connector-1.0.0-beta.43+1.20.1.jar
- industrial-foregoing-1.20.1-3.5.16.jar

### Additions and Modifications

Yes

### Additions and Modifications Description

Adding mods to this performance pack base https://modrinth.com/modpack/hammer/version/1.6.1+1.20.1.neoforge

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Cragsand** [comment]
I messed up and inserted recipe IDs instead of Item IDs, confusing the two.

It should look more like this instead:
https://gist.github.com/Cragsand/b5b3a3c646e936a59f944a5d8753469e
![image](https://github.com/AlmostReliable/almostunified/assets/49168045/79279c7d-b04a-4948-9959-487a2b873e2f)
![image](https://github.com/AlmostReliable/almostunified/assets/49168045/1990641b-6278-43b0-b7ec-721cb5f7c9e1)

I'm still getting tag ownership and ordering incorrect but it's probably my fault for not understanding how to input the syntax properly.
https://gist.github.com/Cragsand/86e2a40e317d364325bb2433fb712237
![image](https://github.com/AlmostReliable/almostunified/assets/49168045/dde981e5-f264-4319-b4f0-4591b7ca1cb6)

Probably not a bug so closing


<blockquote><img src="https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/Cragsand/b5b3a3c646e936a59f944a5d8753469e">gist:b5b3a3c646e936a59f944a5d8753469e</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>
<blockquote><img src="https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/Cragsand/86e2a40e317d364325bb2433fb712237">gist:86e2a40e317d364325bb2433fb712237</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by Cragsand** [comment]
When you add "customTags" or "tagOwnerships" below you also add it to the "tags" list on top.
Otherwise you will get errors like this in the log:
```
[AlmostUnified/]: [TagOwnerships] Owner tag '#forge:dusts/saw' is not present in the unify tag list!
[AlmostUnified/]: [TagOwnerships] Owner tag '#forge:dusts/ender_pearl' is not present in the unify tag list!
```

Something strange I found is that it will sometimes hide all the recipes from JEI when that is not intended like with Ender Pearl Dust. Only the first top recipe should appear while the other ones are hidden. 
So I had to disable hiding recipes, otherwise ALL my different Ender Pearl dusts gets hidden. This is done by: "itemsHidingJeiRei": false 

If anyone else finds this post looking for how to configure rubber, sawdust and ender pears here is my config that unifies:
- Tech Reborn
- Industrial Foregoing 
- Thermal Series

For the following items:
- Cured Rubber / Dry Rubber / Rubber 
- Sawdust
- Ender Pearls
- Bauxite dust / Aluminum dust / Aluminium dust / Crushed Raw Aluminium
- Rubies

```
  "customTags": {
    "custom:rubbers": [
      "techreborn:rubber",
      "industrialforegoing:dryrubber",
      "thermal:cured_rubber"
    ],
	"forge:dusts/bauxite": [
      "immersiveengineering:dust_aluminum",
      "techreborn:bauxite_dust"
    ],
	  "forge:gems/ruby": [
		"forge:rubies",
		"c:rubies"
	  ]
  },
  "tagOwnerships": {  
	  "forge:dusts/wood": [
		"forge:dusts/wood",
		"forge:dusts/sawdust",
		"forge:dusts/saw",
		"c:saw_dusts"
	  ],
	  "forge:dusts/ender_pearl": [
		"forge:dusts/ender_pearl",
		"forge:dusts/ender",
		"c:ender_pearl_dusts"
	  ]
	},
```

Full config: https://gist.github.com/Cragsand/322033866687924850e9a1f1fff2cc21

I probably did this poorly or missed another detail so if anyone wants to feel free to correct this.



<blockquote><img src="https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/Cragsand/322033866687924850e9a1f1fff2cc21">gist:322033866687924850e9a1f1fff2cc21</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by rlnt** [comment]
Ownership tags should not be listed in the reference tags. That's pretty much the only issue I see.
For example your `forge:dusts/wood` tag ownership has to look like this:
```json
	  "forge:dusts/wood": [
		"forge:dusts/sawdust",
		"forge:dusts/saw",
		"c:saw_dusts"
	  ]
```

That way the error from the log will also be gone. Because the requirement for ownership is that the owner tag is a unify tag while all reference tags are not.
