### ISSUE TITLE
Dumping merged items

### ISSUE THREAD

**Issue by Luningor** [AlmostReliable/almostunified#83]
### Describe the feature/addition!

A command to dump the merged tag, along with the merged items and the prevalent item, for debugging purposes.

### Why would like to see this feature/addition?

I'm currently making a modpack that has lots of resources. Most of the duplicates, I handle with AlmostUnified, but for some blocks/items (e.g: minecraft:diamond and gemsnjewels:pale_diamond on forge:diamond) I want to have control over the unification. I know about the ignore list, and about the console dump, but the issue is that once the game starts, there is no way to know what items were merged on the fly, on a comfortable way. The previous example I've stumbled upon on accident, seeing the message on the console in half a second. So I want this feature to not miss on any item I might've wanted on purpose, basically.

**Comment by rlnt** [comment]
I am not sure I am understanding what you are requesting.
The tags that are being unified with their respective items can be seen in the tag dump if you enable that option in the `debug.json` config. You can also see what changes the mod does to which recipes. What information are you missing?

**Comment by Luningor** [comment]
Pardon me, I completely glossed over that file. I'll be checking it out, sorry and thanks for your time.

**Comment by rlnt** [comment]
No worries. Let us know if you need more information.
