### ISSUE TITLE
Undergarden Breaks Torch Recipe when used with Almost Unified

### ISSUE THREAD

**Issue by oliverrook** [AlmostReliable/almostunified#84]
### Minecraft Version

1.20.1

### Mod Version

0.9.4

### Describe the bug!

For some reason, having both this mod and the undergarden mod causes the normal torch recipe to only give 2 torches, not just when using the undergarden wood sticks. It also makes this the default recipe, so even using stuff like polymorph to get past the recipe conflicts is annoying because it requires switching the recipe every time you want to make a torch.

### Additions and Modifications

Yes

### Additions and Modifications Description

I have modified the pack heavily at this point, including adding in Polymorph exactly as a workaround for this issue.
I am using All the Mods 9, but with a lot of extras. That said, I am not the only person having this issue: https://github.com/AllTheMods/ATM-9/issues/1694

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Sounds more like a configuration issue on the mod pack side. They probably unified coal so the custom torch recipe got merged and took priority. Please report that to the pack devs instead.
