### ISSUE TITLE
NeoForge and the transition from "forge:* to" "c:*" namespace

### ISSUE THREAD

**Issue by diefesson** [AlmostReliable/almostunified#89]
### Describe the feature/addition!

Possible solutions:
1. For every "forge:*" create and/or add it to a corresponding "c:*"
  - PRO: high compatibility
  - CON: clustering of repeated tags
3. Replace every "forge:*" with a "c:*tags"
  - PRO: same number of tags as before
  - CON: will cause issues for mods that hard codedly expect a "forge:*" tag

### Why would like to see this feature/addition?

With the new NeoForge stantard to replace the use of the "forge" namespace with "c" many mods will have serious compatibility issues during the transition period.

**Comment by rlnt** [comment]
If mods hardcode a dependency on a `forge` namespace tag, it's on them to fix it. We ship the correct default tags for NeoForge within the `c` namespace. If you are still encountering mods that make use of `forge` tags in recipes, you should report it to them. But as a workaround, you can use our tag substitution (previously tag ownerships) feature to convert all `forge` tags to `c` tags automatically.
