### ISSUE TITLE
[Bug] BetterNether's iron equivalent "cincinnasite" has incorrect crafting recipies

### ISSUE THREAD

**Issue by ezrazazeldev** [AlmostReliable/almostunified#90]
### Minecraft Version

1.21.1

### Mod Version

1.21.1-1.0.0

### Describe the bug!

When crafting iron armor such as leggings or boots with iron, the crafting recipe will output the cincinnasite counterpart. 

### Additions and Modifications

Yes

### Additions and Modifications Description

- Essential Dependencies [0]
- [3d-Skin-Layers](https://modrinth.com/mod/zV5r3pPn) [1.6.7] by tr7zw
- [Accessories Trinkets Compat Layer](https://modrinth.com/mod/TkWgV1AW) [3.10.0+beta.9] by Blodhgarm
- [Accessories](https://modrinth.com/mod/jtmvUHXj) [1.0.0-beta.31+1.21] by Blodhgarm, chyzman, Dr.Zeal
- [Additional Structures](https://modrinth.com/mod/TWsbC6jW) [5.0.0-fabric] by XxRexRaptorxX
- [AlmostUnified](https://modrinth.com/mod/sdaSaQEz) [1.21.1-1.0.0] by Almost Reliable
- [Alternate Current](https://modrinth.com/mod/r0v8vy1s) [1.9.0] by Space Walker
- [AmbientEnvironment](https://modrinth.com/mod/DyTvM1dv) [18.0.0.1] by Jaredlll08
- [AmbientSounds](https://modrinth.com/mod/fM515JnW) [6.0.6] by CreativeMD
- [AppleSkin](https://modrinth.com/mod/EsAfCjCV) [3.0.5+mc1.21] by squeek502
- [Architectury](https://modrinth.com/mod/lhGA9TYQ) [13.0.6] by shedaniel
- [Artifacts](https://modrinth.com/mod/P0Mu4wcQ) [12.0.5] by ochotonida, Florens
- [Axe Effective Skulls [PurpurPack]](https://modrinth.com/mod/S7cHoMDR) [2.0] by Rhythmic, PurpurMC
- [Axes Are Weapons](https://modrinth.com/mod/1jvt7RTc) [1.9.1] by Fourmisain
- [BCLib](https://modrinth.com/mod/BgNRHReB) [21.0.13] by Quiqueck, paulevs, Bulldog83
- [Balm](https://modrinth.com/mod/MBAkmtvl) [21.0.19] by BlayTheNinth
- [Better Advancements](https://modrinth.com/mod/Q2OqKxDG) [0.4.2.19] by way2muchnoise
- [Better Beds](https://modrinth.com/mod/kKwy3HU9) [1.4.0] by Motschen, TeamMidnightDust
- [Better Craftables](https://modrinth.com/mod/BLG002oq) [2.0.0] by Classic36
- [Better Fletching Tables (BFT)](https://modrinth.com/mod/XTJUiumo) [3.0.0] by EclipseStudios, ElGeroIngles
- [Better Ladders](https://modrinth.com/mod/CvgtCmGj) [0.0.3.1.21] by meee
- [Better Nether Map](https://modrinth.com/mod/fdtm99de) [4.0.0-1.21.1] by Jummit
- [Better Nether](https://modrinth.com/mod/MpzVLzy5) [21.0.11] by quiqueck, paulevs (original author)
- [Better Ping Display](https://modrinth.com/mod/MS1ZMyR7) [1.1.1] by Quintinity
- [Better Respawn](https://modrinth.com/mod/ZUQINcGy) [1.21.1-2.0.6] by Max Henkel
- [BetterF3](https://modrinth.com/mod/8shC1gFX) [11.0.2] by cominixo, TreyRuffy
- [BetterHurtCam](https://modrinth.com/mod/o4y0N2hu) [1.9.1+mc1.21] by uku
- [BetterThanMending](https://modrinth.com/mod/Lvv4SHrK) [2.2.0] by Legobmw99
- [Bigger Stack Size](https://modrinth.com/mod/sypq9eA6) [1-v.1.3.2] by Jodek
- [BiomesOPlenty](https://modrinth.com/mod/HXF82T3G) [21.1.0.2] by Adubbz, Forstride
- [Blur+ (Fabric)](https://modrinth.com/mod/NK39zBp2) [4.1.0] by Motschen, tterrag1098, Pyrofab, backryun, byquanton
- [Bow Infinity Fix](https://modrinth.com/mod/BFENfScW) [3.1.0] by Parker8283
- [Capes](https://modrinth.com/mod/89Wsn8GD) [1.5.4+1.21] by Cael
- [Chai's Build Tools](https://modrinth.com/mod/swsFw76C) [1.0.1+1.21] by Chai
- [Chai's Elytra Enchants](https://modrinth.com/mod/kjeo1Vlk) [1.0.3+1.21] by Chai
- [Chat Heads](https://modrinth.com/mod/Wb5oqrBJ) [0.12.10] by dzwdz, Fourmisain
- [Chunks Fade In](https://modrinth.com/mod/JaNmzvA8) [1.0.2-1.21] by Koteinik
- [Chunky](https://modrinth.com/mod/fALzjamp) [1.4.16] by pop4959
- [Client Tweaks](https://modrinth.com/mod/vPNqo58Q) [21.1.1] by BlayTheNinth
- [Cloth Config v15](https://modrinth.com/mod/9s6osm5g) [15.0.130] by shedaniel
- [Clumps](https://modrinth.com/mod/Wnxd13zP) [19.0.0.1] by Jared
- [Collective](https://modrinth.com/mod/e0M1UDsY) [7.84] by Rick South
- [Common Network](https://modrinth.com/mod/HIuqnQpi) [1.0.16-1.21] by Mysticdrew
- [Concurrent Chunk Management Engine](https://modrinth.com/mod/VSNURh3q) [0.3.0+alpha.0.204+1.21.1] by RelativityMC, ishland
- [Continents](https://modrinth.com/mod/bQ5TJA1E) [1.1.5] by Stardust Labs
- [Continuity](https://modrinth.com/mod/1IjD5062) [3.0.0-beta.5+1.21] by PepperCode1
- [Controlling](https://modrinth.com/mod/xv94TkTM) [19.0.1] by Jaredlll08
- [Copper Golem](https://modrinth.com/mod/fvd7vyoL) [1.8.2+1.21] by Sollace
- [Craftable Bell](https://modrinth.com/mod/jypVrveB) [48.1] by Craemon
- [Craftable Bundle](https://modrinth.com/mod/6BricqUj) [48.1] by Craemon
- [Craftable Chainmail](https://modrinth.com/mod/zz8GUPmO) [48.2] by Craemon
- [Craftable Elytra](https://modrinth.com/mod/hYdqvcAu) [48.1] by Craemon
- [Craftable Enchanted Golden Apple](https://modrinth.com/mod/y9Y3cP68) [48.1] by Craemon
- [Craftable Horse Armor](https://modrinth.com/mod/ua9u8yK9) [48.1] by Craemon
- [Craftable Nametag](https://modrinth.com/mod/UgFSv6UG) [48.1] by Craemon
- [Craftable Saddles](https://modrinth.com/mod/c302us4z) [48.1] by Craemon
- [Craftable Trident](https://modrinth.com/mod/j6oNCsqx) [48.2] by Craemon
- [CraftableCapes](https://modrinth.com/mod/wxd6uaXJ) [1.0.3] by Ryhon
- [CreativeCore](https://modrinth.com/mod/OsZiaDHq) [2.12.9] by CreativeMD, AriaFreeze
- [Default Options](https://modrinth.com/mod/WEg59z5b) [21.1.1] by BlayTheNinth
- [Detail Armor Bar](https://modrinth.com/mod/hAt6ty93) [2.6.3+1.21.1-fabric] by RedLime
- [Dimensional Ores](https://modrinth.com/mod/N5XZlKp5) [1.1.0] by Team Council, indeedtough
- [Doors Closed](https://modrinth.com/mod/L49j7sQG) [1.0.0+1.19.4] by Estecka
- [Dragonkind Evolved | End Battle Reborn](https://modrinth.com/mod/yo1bGdBx) [1.5.2] by kanokarob
- [Dungeons and Taverns](https://modrinth.com/mod/tpehi7ww) [1-v4.3] by NovaWostra, Konci, Walls
- [Durability Tooltip](https://modrinth.com/mod/smUP7V3r) [1.1.5] by SuperMartijn642
- [Ears](https://modrinth.com/mod/mfzaZK3Z) [1.4.6] by unascribed
- [Elytra Physics](https://modrinth.com/mod/jfvCMH0K) [2.1_mc1.19.3+] by ImJoshh_
- [Emoji Type](https://modrinth.com/mod/q7vRRpxU) [2.2.7-1.21.1] by CyborgCabbage, Norbiros
- [Enchantment Lore](https://modrinth.com/mod/YHdR6hMt) [1.4.1] by supersaiyansubtlety
- [End Remastered](https://modrinth.com/mod/ZJTGwAND) [6.0.2] by Jack Bagel
- [Enhanced Attack Indicator](https://modrinth.com/mod/eTy17BBS) [1.0.4+1.21] by Minenash
- [EntityCulling](https://modrinth.com/mod/NNAgCjsB) [1.7.0] by tr7zw
- [Expanded Axe Enchanting](https://modrinth.com/mod/nmJ9dZtI) [1.0.11] by SmushyTaco
- [Explorify](https://modrinth.com/mod/HSfsxuTo) [1.6.1] by bebebea_loste
- [Explosive Enhancement](https://modrinth.com/mod/OSQ8mw2r) [1.2.3-1.21.0] by Superkat32
- [Extended Drawers](https://modrinth.com/mod/AhtxbnpG) [3.0.3+mc.1.21.1] by MattiDragon
- [Fabric API](https://modrinth.com/mod/P7dR8mSH) [0.103.0+1.21.1] by FabricMC
- [Fabric Language Kotlin](https://modrinth.com/mod/Ha28R6CL) [1.12.1+kotlin.2.0.20] by FabricMC
- [Falling Leaves](https://modrinth.com/mod/WhbRG4iK) [1.16.2] by Fourmisain, BrekiTomasson, RandomMcSomethin
- [Farmer's Delight](https://modrinth.com/mod/7vxePowz) [1.21-2.1.7+refabricated] by MehVahdJukaar, MerchantPug
- [Fast IP Ping](https://modrinth.com/mod/9mtu0sUO) [1.0.4] by Fallen_Breath
- [Fast Paintings](https://modrinth.com/mod/z3TzcquW) [1.21-1.2.9] by MehVahdJukaar
- [FastQuit](https://modrinth.com/mod/x1hIzbuY) [3.0.0+1.20.6] by KingContaria
- [FerriteCore](https://modrinth.com/mod/uXXizFIs) [7.0.0] by malte0811
- [Fixed Levels](https://modrinth.com/mod/CCDuht84) [1.3.0+1.21] by neptunecentury
- [Formations Nether](https://modrinth.com/mod/cGvQGRls) [1.0.5] by SuperMartijn642
- [Formations Overworld](https://modrinth.com/mod/KX1XC0Oo) [1.0.4] by SuperMartijn642
- [Formations](https://modrinth.com/mod/tPe4xnPd) [1.0.2] by SuperMartijn642
- [Friends&Foes - Beekeeper Hut](https://modrinth.com/mod/Kt4RVKEd) [2.0.1] by Faboslav
- [Friends&Foes - Flowery Mooblooms](https://modrinth.com/mod/ECOSu6pa) [2.0.2] by Faboslav
- [Friends&Foes](https://modrinth.com/mod/POQ2i9zu) [2.0.16] by Faboslav
- [Fzzy Config](https://modrinth.com/mod/hYykXjDp) [0.3.7+1.21] by fzzyhmstrs
- [GUI Clock](https://modrinth.com/mod/g1yXisD2) [4.6] by Rick South
- [GUI Compass](https://modrinth.com/mod/ZORMkttv) [4.8] by Rick South
- [GUI Followers](https://modrinth.com/mod/hTGmExq6) [3.8] by Rick South
- [GlitchCore](https://modrinth.com/mod/s3dmwKy5) [2.1.0.0] by Adubbz
- [Healing Campfire](https://modrinth.com/mod/kOuPUitF) [6.1] by Rick South
- [Held Item Info](https://modrinth.com/mod/tEcWzCZz) [1.7.0] by Neecko5b84
- [Icarus](https://modrinth.com/mod/Dw7M6XKW) [4.0.1] by Cammie, Up
- [Improved Anvils](https://modrinth.com/mod/xjFXbsyG) [1.0.6-1.21] by DavidJMacDonald
- [Improved Sign Editing](https://modrinth.com/mod/EWQifKYI) [1.4] by Rick South
- [Indium](https://modrinth.com/mod/Orvt0mRa) [1.0.35+mc1.21] by comp500
- [Infinite Trading](https://modrinth.com/mod/U3eoZT3o) [4.5] by Rick South
- [Infinity Mending Bows [PurpurPack]](https://modrinth.com/mod/NLzRxVcC) [1.0] by Rhythmic
- [Inventory Essentials](https://modrinth.com/mod/Boon8xwi) [21.1.1] by BlayTheNinth
- [Inventory Totem](https://modrinth.com/mod/yQj7xqEM) [3.3] by Rick South
- [Iris](https://modrinth.com/mod/YL57xq9U) [1.8.0-beta.3+mc1.21.1] by coderbot, IMS212, Justsnoopy30, FoundationGames
- [Jade](https://modrinth.com/mod/nvQzSEkH) [15.3.0+fabric] by Snownee
- [JamLib](https://modrinth.com/mod/IYY9Siz8) [1.0.11+1.21] by Jamalam
- [Just Enough Breeding](https://modrinth.com/mod/9Pk89J3g) [1.4.0] by Christofmeg
- [Just Enough Items](https://modrinth.com/mod/u6dRKJwZ) [19.15.0.149] by mezz
- [Kiwi Library](https://modrinth.com/mod/ufdDoWPd) [15.1.0+fabric] by Snownee
- [Ksyxis](https://modrinth.com/mod/2ecVyZ49) [1.3.2] by VidTu
- [Leaf Me Alone](https://modrinth.com/mod/ppMUvsIg) [1.0.1] by Nord_Act
- [Leaves Us In Peace](https://modrinth.com/mod/IIpWIe1o) [1.1.3] by Tfarecnim, supersaiyansubtlety
- [Lithium](https://modrinth.com/mod/gvQqBUqZ) [0.13.0] by JellySquid, 2No2Name
- [Longer Chat History](https://modrinth.com/mod/f4P7fNKN) [1.5] by Golem
- [M.R.U](https://modrinth.com/mod/SNVQ2c0g) [s99KEPTF]
- [MaLiLib](https://modrinth.com/mod/GcWjdA9I) [0.21.0] by masa
- [MidnightLib](https://modrinth.com/mod/codAaoxh) [1.6.1] by Motschen, TeamMidnightDust
- [MixinTrace](https://modrinth.com/mod/sGmHWmeL) [1.1.1+1.17] by comp500
- [Mod Menu](https://modrinth.com/mod/mOgUt4GM) [11.0.2] by Prospector, haykam821, TerraformersMC
- [Model Gap Fix](https://modrinth.com/mod/QdG47OkI) [1.21-1.6] by MehVahdJukaar
- [MonoLib](https://modrinth.com/mod/9leXt4A5) [1.3.0] by Jason13
- [Monsters in the Closet](https://modrinth.com/mod/GMA8jFBD) [1.0.3+1.21] by Minenash
- [Moonlight Lib](https://modrinth.com/mod/twkfQtEc) [1.21-2.14.12] by MehVahdJukaar
- [More Barrel Variants](https://modrinth.com/mod/g4AhyGgi) [1.6.0] by pnku, LieOnLion
- [More Bed Variants](https://modrinth.com/mod/nKaiA11S) [1.3.0] by pnku, LieOnLion
- [More Beehive Variants](https://modrinth.com/mod/evbwy51Z) [1.0.0] by pnku, LieOnLion
- [More Bows and Arrows](https://modrinth.com/mod/E8mxlh6j) [3.1.0] by Lupin, Jason13
- [More Cartography Tables](https://modrinth.com/mod/pEwUc4MK) [1.5.7] by pnku, LieOnLion
- [More Chat History](https://modrinth.com/mod/8qkXwOnk) [1.3.1] by JackFred
- [More Chest Variants](https://modrinth.com/mod/HKKqmr2p) [1.5.6] by LieOnLion
- [More Chiseled Bookshelf Variants](https://modrinth.com/mod/vkun3O1z) [1.6.1] by pnku, LieOnLion
- [More Composter Variants](https://modrinth.com/mod/vDjDgFj7) [1.6.3] by pnku, LieOnLion
- [More Culling](https://modrinth.com/mod/51shyZVL) [0.27.1] by FX - PR0CESS
- [More Fletching Tables](https://modrinth.com/mod/8TnTa9Ui) [1.5.7] by pnku, LieOnLion
- [More Furnace Variants](https://modrinth.com/mod/aFKTqsnr) [1.0.3] by LieOnLion
- [More Grindstone Variants](https://modrinth.com/mod/VNYXl8f7) [1.0.2] by pnku, LieOnLion
- [More Jukebox/Noteblock Variants](https://modrinth.com/mod/CLgavC7x) [1.0.2] by pnku, LieOnLion
- [More Ladders](https://modrinth.com/mod/cs6FaYWt) [1.7-1.21.1] by Boczek
- [More Lectern Variants](https://modrinth.com/mod/pLsa93bN) [1.6.0] by pnku, LieOnLion
- [More Loom Variants](https://modrinth.com/mod/yM3Gl0Pb) [1.0.0] by pnku, LieOnLion
- [More Smithing Tables](https://modrinth.com/mod/t3iWfx17) [1.1.0] by pnku, LieOnLion
- [More Smoker Variants](https://modrinth.com/mod/8HxZnUY7) [1.1.1] by pnku, LieOnLion
- [MoreCursors](https://modrinth.com/mod/dMSwti7t) [1.0.3] by 557
- [Mouse Tweaks](https://modrinth.com/mod/aC3cM3Vq) [2.26] by Ivan Molodetskikh (YaLTeR)
- [NetherPortalFix](https://modrinth.com/mod/nPZr02ET) [21.1.1] by BlayTheNinth
- [New Slab Variants](https://modrinth.com/mod/ns0BvMIG) [2.1.0] by Lupin, Jason13
- [Not Enough Recipe Book](https://modrinth.com/mod/bQh7xzFq) [0.4.1] by OctoStudios
- [NotEnoughAnimations](https://modrinth.com/mod/MPCX6s5C) [1.7.5] by tr7zw
- [OctoLib](https://modrinth.com/mod/RH2KUdKJ) [0.4.2] by OctoStudios
- [On Soul Fire](https://modrinth.com/mod/HfTvoVqY) [1.21-r1] by MoriyaShiine
- [Oxify](https://modrinth.com/mod/TdwbBPLt) [1.21.1-1.2.0] by CodeINN95612
- [Packet Fixer](https://modrinth.com/mod/c7m1mi73) [1.4.1] by TonimatasDEV
- [Particle Core](https://modrinth.com/mod/RSeLon5O) [0.2.4+1.21] by fzzyhmstrs
- [Particle Rain](https://modrinth.com/mod/nrikgvxm) [2.1.4] by PigCart
- [Particular](https://modrinth.com/mod/B1CcCd9h) [1.1.1+1.21] by Chai
- [Passive Shield](https://modrinth.com/mod/iQBrasyH) [3.6] by Rick South
- [Philip`s Ruins](https://modrinth.com/mod/KdJhOYVV) [1.21.1] by Philip
- [Placeholder API](https://modrinth.com/mod/eXts2L7r) [2.4.1+1.21] by Patbox
- [PolydexBridge](https://modrinth.com/mod/cjSHexOj) [1.0.1+mc.1.21.1] by MattiDragon
- [Polydex](https://modrinth.com/mod/m5NB7FJE) [1.2.3+1.21] by Patbox
- [Polymer](https://modrinth.com/mod/xGdtZczs) [0.9.12+1.21.1] by Patbox
- [Presence Footsteps](https://modrinth.com/mod/rcTfTZr3) [1.10.0+1.21] by Hurricaaane (Ha3), Sollace
- [Presencium](https://modrinth.com/mod/iNU1UQcw) [2.2] by splittque
- [Quad](https://modrinth.com/mod/7jzrCiK0) [1.3.0-beta.4] by LieOnLion
- [Raised](https://modrinth.com/mod/nCQRBEiR) [4.0.0] by yurisuika
- [Random Misfits](https://modrinth.com/mod/sdjh3tKn) [1.21.1-1.1.9-fabric] by jahirtrap
- [Reese's Sodium Options](https://modrinth.com/mod/Bh37bMuy) [1.8.0-beta.2+mc1.21.1] by FlashyReese
- [Remove Reloading Screen](https://modrinth.com/mod/ZP7xHXtw) [5.0.7+mc1.21-fabric] by dima_dencep
- [Repurposed Structures](https://modrinth.com/mod/muf0XoRe) [7.5.9+1.21.1-fabric] by TelepathicGrunt
- [Resourcefulconfig](https://modrinth.com/mod/M1953qlQ) [3.0.3] by ThatGravyBoat
- [Resourcify](https://modrinth.com/mod/RLzHAoZe) [1.4.1] by DeDiamondPro
- [Respawnable Pets](https://modrinth.com/mod/gbFe1FWa) [1.21-r1] by MoriyaShiine, cybercat5555
- [Ride Hud](https://modrinth.com/mod/Fws3jl2f) [1.3.4+1.21] by TreSet
- [Right Click Harvest](https://modrinth.com/mod/Cnejf5xM) [4.3.1+1.21] by Jamalam
- [Searchables](https://modrinth.com/mod/fuuu3xnx) [1.0.1] by Jaredlll08
- [Snow Under Trees](https://modrinth.com/mod/XVnUIUAQ) [2.5.3+1.21] by IMB11 (mineblock11), DeadlyMC, bl4ckscor3
- [Snow! Real Magic!](https://modrinth.com/mod/iJNje1E8) [11.0.3+fabric] by Snownee
- [Sodium Dynamic Lights](https://modrinth.com/mod/PxQSWIcD) [1.0.0] by toni
- [Sodium Extra](https://modrinth.com/mod/PtjYWJkn) [0.6.0-beta.1+mc1.21.1] by FlashyReese
- [Sodium Extras](https://modrinth.com/mod/vqqx0QiE) [1.0.0] by toni
- [Sodium Shadowy Path Blocks](https://modrinth.com/mod/EIa1eiMm) [4.0.0-beta.1] by Rynnavinx
- [Sodium](https://modrinth.com/mod/AANobbMI) [0.6.0-beta.1+mc1.21] by @jellysquid3
- [Sound Physics Remastered](https://modrinth.com/mod/qyVF9oeo) [1.21.1-1.4.6] by Sonic Ether, vlad2305m, Max Henkel, Saint
- [Status Effect Bars](https://modrinth.com/mod/x02cBj9Y) [1.0.6] by Neecko5b84
- [SuperMartijn642's Config Library](https://modrinth.com/mod/LN9BxssP) [1.1.8] by SuperMartijn642
- [SwingThrough](https://modrinth.com/mod/JyKlunuD) [1.0.5+1.21] by Sisby folk
- [Tectonic](https://modrinth.com/mod/lWDHr9jE) [2.4.1a] by Apollo
- [TerraBlender](https://modrinth.com/mod/kkmrDlKT) [4.1.0.2] by Adubbz
- [ThreatenGL](https://modrinth.com/mod/RSFrpoou) [1.3.3-release.1] by Richy Z, Numelon
- [Tidal Towns](https://modrinth.com/mod/EEIwvQVo) [1.3.3] by joshieman
- [Tiny Item Animations](https://modrinth.com/mod/wMkevcSR) [1.2.1] by Trivaxy
- [ToastBegone](https://modrinth.com/mod/g8reZf3x) [1.2.0] by Raxdiam
- [Tom's Simple Storage Mod](https://modrinth.com/mod/XZNI4Cpy) [2.0.9] by tom5454
- [Totem of Infinity](https://modrinth.com/mod/T3niFhcB) [1.2.1] by andw20
- [Trade Cycling](https://modrinth.com/mod/qpPoAL6m) [1.21.1-1.0.14] by Max Henkel
- [Tweakeroo](https://modrinth.com/mod/t5wuYk45) [0.21.50] by masa
- [Universal Graves](https://modrinth.com/mod/yn9u3ypm) [3.4.3+1.21] by Patbox
- [Unlock All Recipes](https://modrinth.com/mod/rGdirrbP) [48.2] by Craemon
- [Vanilla Config](https://modrinth.com/mod/vtYpD93u) [1.2.11+1.21] by TreSet
- [VisualOverhaul](https://modrinth.com/mod/YQnwl5Vv) [5.2.1] by Motschen, TeamMidnightDust
- [Visuality](https://modrinth.com/mod/rI0hvYcd) [0.7.7+1.21] by PinkGoosik
- [Waystones](https://modrinth.com/mod/LOpKHB2A) [21.1.2] by BlayTheNinth
- [Wilder Wild](https://modrinth.com/mod/AtHRJSUW) [2.4.16-mc1.21.1] by Lunade, Treetrain1, Soro
- [WorldWeaver](https://modrinth.com/mod/RiN8rDVs) [21.0.13] by Quiqueck
- [Xaero's Minimap](https://modrinth.com/mod/1bokaNcj) [24.3.0] by xaero96
- [Xaero's World Map](https://modrinth.com/mod/NcUtCpym) [1.39.0] by xaero96
- [XaeroPlus](https://modrinth.com/mod/EnPUzSTg) [2.23] by rfresh2
- [You May Rest Now](https://modrinth.com/mod/L5HSiSqi) [1.0.0+1.21] by Jamalam
- [e4mc](https://modrinth.com/mod/qANg5Jrr) [5.1.0] by skyevg
- [essential-container](https://modrinth.com/mod/k2ZPuTBm) [1.0.0]
- [oωo](https://modrinth.com/mod/ccKDOlHs) [0.12.10+1.21] by glisco
- [spark](https://modrinth.com/mod/l6YH9Als) [1.10.97] by Luck
- [ukulib](https://modrinth.com/mod/Y8uFrUil) [1.4.0+1.21] by uku

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
This is not a mod issue or a bug. It's normal behavior because Better Nether and Better End have items they tagged with the iron tag. This is just a configuration problem. To solve that, you can put their items onto the ignore list with something like this:
`"ignored_items": [".*thallasium.*", ".*cincinnasite.*"]`

**Comment by ezrazazeldev** [comment]
Ah, my bad then. Thanks for the help!
