### ISSUE TITLE
Recent Version of JEI is unliked by AU

### ISSUE THREAD

**Issue by ChaosDogG** [AlmostReliable/almostunified#93]
### Minecraft Version

1.19.2

### Mod Version

0.8.1

### Crash Report

https://gist.github.com/ChaosDogG/6f063db70d143d3d2993deb1439e95e2

### Additions and Modifications

Yes

### Additions and Modifications Description

Whenever I click on anything in the JEI menu to check its recipes/uses, the game just dies. i was told by JEI's main dev to come here since they say it's on your end. [https://github.com/mezz/JustEnoughItems/issues/3775](url)

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by mezz** [comment]
I backported the decorator features to JEI 1.19.2 today to help with this issue, so it should be possible to remove the JEI mixin for this version like in 1.20+.
 * https://github.com/mezz/JustEnoughItems/pull/3255 
 
It's available in JEI `11.8.0.+`

**Comment by ChaosDogG** [comment]
Oh? I'll try it tomorrow!

**Comment by ChaosDogG** [comment]
~~or, later today for me-~~

**Comment by mezz** [comment]
Sorry @ChaosDogG, that message was meant for the developers of this mod. 
They will need to integrate with this new version of JEI before the bug is fixed.

**Comment by ChaosDogG** [comment]
Oop-
Alright, thanks for clearin that up b4 i rolled myself, lolol

**Comment by rlnt** [comment]
Mezz 😭 how dare you backport my own JEI PR and break an old version I didn't plan on updating anymore.

**Comment by mezz** [comment]
Hey you're the one mixing into other mods :P
I'll see what I can do haha

**Comment by rlnt** [comment]
I wasn't a fan of that either, that's why I PRed the recipe decorators 😄
Good thing is I can finally yeet the mixin plugin.

**Comment by rlnt** [comment]
Thanks for the report. The new version with the fix was just released and should be available in a bit.

**Comment by ChaosDogG** [comment]
Awesome, thanks!

**Comment by mezz** [comment]
Great, thanks for the quick fix!
