### ISSUE TITLE
Loot table unification

### ISSUE THREAD

**Issue by Luningor** [AlmostReliable/almostunified#95]
### Describe the feature/addition!

To unify items in loot tables, as in, if a loot table has a gem (let's say, exmod:sapphire under #forge:gems/sapphire) and I want to unify all sapphires in that tag into loremipsum:sapphire, the loot table that had the original one to roll for the new one.

### Why would like to see this feature/addition?

So as to not have a way to get the old item, and not have to manually replace every loot table that involves an unified item (which, in a moderate enough modpack, may entail going through the combined efforts of searching through many mods, then many tables for blocks, entities, and chests).

**Comment by rlnt** [comment]
This feature already exists in 1.21+. We don't do any backports for 1.20.1 anymore though. It only receives critical bug fixes.
