### ISSUE TITLE
No 1.21 version?

### ISSUE THREAD

**Issue by Wizardon777** [AlmostReliable/almostunified#96]
### Describe the feature/addition!

I see a 1.21.1 version, but not 1.21, is that correct?

### Why would like to see this feature/addition?

working on 1.21 modpacks.

**Comment by rlnt** [comment]
I think 99% of mods on 1.21 are compatible with 1.21.1. I am not sure why you stick to the major version but you are correct, we are not explicitly providing a version for 1.21. We also don't plan to. Sorry for the inconvenience.
