### ISSUE TITLE
[Crash] - 1.21.1-1.2.0 - Cannot invoke "com.almostreliable.unified.core.AlmostUnifiedRuntimeImpl.getDebugHandler()"

### ISSUE THREAD

**Issue by muggleorwizard** [AlmostReliable/almostunified#99]
### Minecraft Version

1.21.1

### Mod Version

1.21.1-1.2.0

### Crash Report

https://pastebin.com/sY6Uncf5

### Log

https://pastebin.com/eCWg1Q5D

### Additions and Modifications

Yes

### Additions and Modifications Description

Mod List: https://pastebin.com/BWHHSjPs
No configs modified
Note: Crash occurs with stellaris-1.21-neoforge-1.1.6. Crash does not occur with stellaris-1.21-neoforge-1.1.5. Making a report on the stellaris github page as well. https://github.com/st0x0ef/stellaris/issues/41
Crash occurred when clicking trying to create a new world.

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Stellaris issue, I answered on the other issue. Thanks for reporting. We need to wait for an update on their end.
